Repository OpenVoiceOS/ovos-skill-volume, pull requests merged in 2022-10, with the labels that each got.

#12 fix imports
  setup.py
Labels: bug

#13 Feat/automations
  .github/workflows/auto_translate.yml
  .github/workflows/build_tests.yml
  .github/workflows/license_tests.yml
  .github/workflows/unit_tests.yml
  requirements.txt
  scripts/prepare_skillstore.py
  scripts/translate.py
  test/unittests/osm_tests.py
  test/unittests/plugin_tests.py
  test/unittests/test_skill_loading.py
Labels: automations

#14 german translation review
  locale/de-de/change_volume.voc
  locale/de-de/current_volume.voc
  locale/de-de/default_volume.intent
  locale/de-de/high_volume.intent
  locale/de-de/increase_volume.voc
  locale/de-de/less_volume.voc
  locale/de-de/low_volume.intent
  locale/de-de/max.volume.dialog
  locale/de-de/max_volume.intent
  locale/de-de/mute.intent
  locale/de-de/set.volume.percent.dialog
  locale/de-de/toggle_mute.intent
  locale/de-de/unmute.intent
  locale/de-de/volume.is.dialog
Labels: enhancement
